### ISSUE TITLE
Indentation on both sides

### ISSUE THREAD

**Issue by eg9** [mbertucci47/keytheorems#8]
A request that users sometimes do is to indent statements (or examples) on either side, like a block quote. See, for instance https://tex.stackexchange.com/q/235925/4427 and comments to my (recently edited) answer.

I believe it would be a good addition to your very useful and rich package.

**Comment by mbertucci47** [comment]
I'll take a look and see if I can push something in the next few days. Thanks for the report!

**Comment by mbertucci47** [comment]
@eg9 By using `\list` instead of `\trivlist` the `\@listdepth` count is changed, which changes things like vertical spacing between items of inner lists (depends on definition of `\@listi`, `\@listii`, and so on). Would you suggest keeping this or changing your patch to something like
```tex
\usepackage{etoolbox}
\usepackage{lipsum}
\usepackage{amsthm}

\theoremstyle{definition}
\newtheorem{innerexample}{Example}

\makeatletter
%\patchcmd{\endinnerexample}{\endtrivlist}{\endlist}{}{} % COMMENTED
\newenvironment{example}
 {\patchcmd{\@thm}{\trivlist}{\list{}{%
   \leftmargin=3em
   \rightmargin=3em
   \global\advance\@listdepth\m@ne
   }}{}{}%
  \innerexample}
 {\endinnerexample}
\makeatother
```
The `\endtrivlist` patch is commented because `\endlist` is just
```tex
\def\endlist{%
  \global\advance\@listdepth\m@ne
  \endtrivlist}
```
and we've already subtracted one from `\@listdepth`.

I think I'd like to keep the `\trivlist` behavior of not setting `\@list<num>` but if you have a good reason otherwise I'd be happy to listen.

**Comment by mbertucci47** [comment]
Implemented in https://github.com/mbertucci47/keytheorems/commit/06ab360f1c5e73071b38fda261d61d429872a016. Patching is very sensitive to changes to `\@thm` like by cleveref and theoremref so some branching was necessary. I decided to set `\listparindent` and `\parsep` to whatever the values are where the theorem is called. And decreased the value of `\@listdepth` as discussed above.

**Comment by mbertucci47** [comment]
For posterity: It would be nice to do something like
```tex
\let\orig@thm\@thm
```
then in the prehead hook
```tex
\def\@thm#1#2#3{%
  \begingroup
  \def\trivlist{<my def>}
  \orig@thm{#1}{#2}{#3}
  \endgroup}
```
but this doesn't work because `\@thm` looks ahead for more arguments when it's used.

**Comment by mbertucci47** [comment]
Greatly simplified in https://github.com/mbertucci47/keytheorems/commit/4a0f2d8816d8f30221d22360fe369e70f156be5c. Patching not required

**Comment by mbertucci47** [comment]
Added in v0.2.1 which has been pushed to CTAN
